In [1]:
"""
    날짜 : 2020/08/10
    이름 : 김동욱
    내용 : Numpy(수치 해석 패키지) 실습하기
"""

'\n    날짜 : 2020/08/10\n    이름 : 김동욱\n    내용 : Numpy(수치 해석 패키지) 실습하기\n'

In [3]:
import numpy as np

In [6]:
#백터 생성
v1 = np.array([1, 2, 3 ,4 ,5])
v1

array([1, 2, 3, 4, 5])

In [9]:
v2 = np.arange(5)
v2

array([0, 1, 2, 3, 4])

In [13]:
#0 ~ 1 사이 임의의 실수 100개
rand1 = np.random.rand(100)
rand1

array([0.50353694, 0.90226692, 0.48748818, 0.8718075 , 0.27993675,
       0.86113221, 0.89313905, 0.16953292, 0.89741804, 0.59166548,
       0.27538415, 0.98058257, 0.44585266, 0.50448344, 0.79907954,
       0.83108568, 0.57251287, 0.34209046, 0.95587496, 0.63039728,
       0.50363381, 0.66151238, 0.91756388, 0.50570125, 0.38688927,
       0.90522738, 0.51701232, 0.32421918, 0.22694481, 0.2409292 ,
       0.99278037, 0.21909383, 0.01846637, 0.37834458, 0.29906132,
       0.17203189, 0.56757285, 0.36793384, 0.10412997, 0.47639965,
       0.21596318, 0.05451743, 0.02501866, 0.02774055, 0.47705315,
       0.3257996 , 0.60274623, 0.20407425, 0.01227964, 0.92757868,
       0.62850827, 0.80516888, 0.0582579 , 0.11685132, 0.38697448,
       0.27158735, 0.16675843, 0.13164276, 0.35789808, 0.59518939,
       0.16345694, 0.18419059, 0.8983441 , 0.28698621, 0.17317339,
       0.36170306, 0.3633493 , 0.36905236, 0.57866408, 0.32372815,
       0.07325865, 0.28475171, 0.8388657 , 0.19147394, 0.21599

In [15]:
#표준 정규분포를 따르는 실수 100개
rand2 = np.random.randn(100)
rand2

array([ 0.46043421, -1.72712255,  2.39734802,  1.71340928,  1.94514876,
       -0.56824556, -0.10007513, -1.38843391, -0.05701511,  0.39838778,
       -0.52268615,  0.84548036,  1.04724779,  0.88843485,  0.491628  ,
       -1.13456747, -0.88069325, -0.97740555, -0.09164672, -0.2379682 ,
        0.31238264,  0.46477938, -0.47522863,  0.53380487,  0.67722728,
        0.36148815,  0.23689136, -0.46126882,  0.94235933,  0.32755504,
       -0.44300556,  0.99073292,  0.87351993,  1.10151181,  0.06615735,
        0.54306422,  0.41724986, -0.66244481, -0.51686133,  0.24421906,
        1.12978575, -1.94911217, -0.35741099, -0.62858638,  0.86100954,
       -0.28961247, -0.31314563, -1.78706346,  1.36980046,  0.94086061,
       -1.59989748, -1.34105547,  0.33146346,  0.22844488, -1.14916855,
       -1.07417061,  0.07649713, -0.32928723,  0.36051298, -1.1977459 ,
        1.85924579,  0.6486973 , -2.25322415,  0.60781395,  1.1291882 ,
        0.61522503, -1.09121197,  2.0814543 ,  0.13579657,  0.80

In [17]:
#평균 0, 표준편차가 1인 정규분포를 따르는 임의의 실수 100개
rand3 = np.random.normal(0, 1, 100)
rand3

array([ 0.77680247,  0.77420182,  1.16061956,  1.90721882, -0.07013544,
       -1.23328069,  0.62673561,  1.32053777, -1.09865506,  0.69317906,
        0.37010301, -1.30995717, -2.05972968, -0.15230659,  0.44351884,
       -0.43363805,  1.68260199, -0.18137024,  0.47794772, -0.57903593,
        0.47280598, -1.52514628, -1.13402208, -0.90269764,  0.75073478,
       -1.26307024, -0.62178789,  0.12668777, -0.9250079 ,  0.87907269,
       -0.11468161, -0.93446082,  0.04538743,  0.82544365,  0.75996585,
        0.84372147,  2.48109655,  0.19921077,  0.36502833, -2.70465243,
        1.46714597,  0.61866068,  0.13231718, -0.42784731, -1.69098129,
       -0.73170353,  0.85426139,  0.11557813,  1.03501098,  0.90851327,
        0.65972604,  0.54426221, -1.52254109, -0.20633648, -0.42673757,
       -0.69915355,  1.4395614 ,  0.1685335 , -1.75165698,  0.59357861,
        0.10040916, -1.49380328, -0.96197481, -0.94385141,  0.84266675,
       -0.29563365, -0.49107127,  0.34770249, -0.22214026,  1.22